import {setupGame} from '../../assets/mini-game.js';
import {PartyClient} from '../../assets/party-client.mjs';
import {Practice} from './practice.mjs';
const ui=setupGame('quiz','Quiz Party'),$=s=>document.querySelector(s),notice=s=>$('#notice').textContent=s;
let mode='menu',practice=null,state=null,offset=0,lastTime=performance.now(),announced='',loading=false,visibleQuestion='';
const client=new PartyClient('quiz',s=>{if(mode!=='online')return;state=s;offset=s.serverNow-Date.now();render();},()=>{},notice);
if(self!==top)$('main').classList.add('embedded');for(let i=0;i<6;i++){const o=document.createElement('option');o.value=i;o.textContent=['Focus','Surprise','Smile','Win','Sad','Laugh'][i];$('#avatar').append(o);}
const current=()=>mode==='practice'?practice.snapshot():state;
function render(){const s=current();if(!s)return;$('#room').hidden=false;$('#lobby').hidden=true;const solo=mode==='practice',closed=solo?s.phase!=='question':['quizReveal','finished'].includes(s.phase),final=s.phase==='finished';
 $('#room').dataset.active=String(s.phase!=='lobby');$('#online-controls').hidden=solo;$('#host-tools').hidden=solo||s.host!==s.you;$('#start').disabled=!['lobby','finished'].includes(s.phase);$('#start').textContent=final?'Rematch':'Start match';$('#lock').textContent=s.locked?'Unlock room':'Lock room';$('#pause').hidden=!solo||closed;$('#pause').textContent=s.paused?'Resume':'Pause';
 $('#phase').textContent=final?'Final results':s.paused?'Paused':closed?'Answer explained':s.phase==='lobby'?'Waiting for friends':'Choose your answer';$('#round').textContent=s.round?'Question '+s.round+' / 10':(solo?'':'Host starts when 2–8 players are connected.');$('#question').textContent=s.question?.text||'Ready for a quiz?';$('#answers').replaceChildren();
 for(const [i,answer]of(s.question?.options||[]).entries()){const b=document.createElement('button');b.textContent=(i+1)+'. '+answer;b.disabled=s.phase!=='question'||s.selection!==null||s.paused||(!solo&&client.socket?.readyState!==1);b.classList.toggle('selected',s.selection===i);b.classList.toggle('correct',closed&&s.question.correct===i);b.onclick=()=>answerQuestion(i);$('#answers').append(b);}
 $('#feedback').textContent=closed?(s.selection===s.question?.correct?'Correct!':s.selection===null?'No answer submitted.':'Not this time.'):(s.selection!==null?'Answer locked. Waiting for the question to close.':solo?'Choose with a click, tap, or keys 1–4.':(s.answered?.length||0)+' / '+(s.eligible?.length||0)+' answered.');
 $('#explanation').hidden=!closed;$('#explain').textContent=s.question?.explanation||'';if(closed)$('#source').href=s.question.source;else $('#source').removeAttribute('href');
 $('#next').hidden=!(solo?s.phase==='reveal':s.phase==='quizReveal'&&s.host===s.you);$('#retry').hidden=!solo||!final;$('#players').replaceChildren();
 const players=solo?[{name:'You',score:s.score,avatar:0,connected:true}]:[...s.players].sort((a,b)=>b.score-a.score);for(const p of players){const li=document.createElement('li');const file=ui.theme.avatars?.[p.avatar];if(file){const img=document.createElement('img');img.src=ui.profile.assets+file;img.alt='';li.append(img);}const label=document.createElement('span');label.textContent=p.name+(!p.connected?' · disconnected':'')+(p.id===s.host?' (host)':'');const score=document.createElement('strong');score.textContent=p.score;li.append(label,score);$('#players').append(li);}
 $('#best').textContent=solo?'Practice best: '+ui.read('best'):'';$('#connection').textContent=solo?'':s.reason||'Disconnected seats are reserved for 60 seconds. The timer continues; leave or reconnect below. A departing host passes control to a connected player.';
 const questionKey=s.phase==='question'?mode+':'+(s.roundId||s.round):'';
 if(questionKey&&questionKey!==visibleQuestion)$('#question').scrollIntoView({block:'start',behavior:'instant'});
 visibleQuestion=questionKey;
 const event=s.round+':'+s.phase;if(closed&&announced!==event){announced=event;ui.expression(s.selection===s.question?.correct?'win':'lose');ui.react(final?'win':s.selection===s.question?.correct?'milestone':'lose');if(solo&&final&&s.score>ui.read('best')){$('#storage-note').hidden=ui.write('best',s.score);$('#best').textContent='Practice best: '+Math.max(s.score,ui.read('best'));}}tickText();
}
function tickText(){const s=current();$('#timer').textContent=mode==='practice'&&s?.phase==='question'?Math.ceil(s.remaining/1000)+'s':mode==='online'&&s?.deadline?Math.max(0,Math.ceil((s.deadline-Date.now()-offset)/1000))+'s':'';}
function answerQuestion(i){if(mode==='practice'){if(practice.finish(i))render();}else client.send('answer',{choice:i});}
async function solo(){if(loading)return;loading=true;$('#practice').disabled=true;try{const response=await fetch('./practice.json');if(!response.ok)throw Error('Practice questions could not load.');const pack=await response.json();for(const q of pack){const order=[0,1,2,3];for(let i=3;i>0;i--){const j=Math.floor(Math.random()*(i+1));[order[i],order[j]]=[order[j],order[i]];}q.options=order.map(i=>q.options[i]);q.correct=order.indexOf(q.correct);}practice=new Practice(pack);mode='practice';announced='';lastTime=performance.now();notice('Solo practice. Pause whenever you need.');ui.react('start');render();}catch(e){notice(e.message);}finally{loading=false;$('#practice').disabled=false;}}
async function enter(create){if(loading)return;loading=true;$('#create').disabled=$('#join').disabled=true;try{mode='online';state=null;client.state=null;$('#invite').value=await client.enter(create,$('#name').value,Number($('#avatar').value));ui.react('start');}catch(e){notice(e.message);mode='menu';}finally{loading=false;$('#create').disabled=$('#join').disabled=false;}}
$('#practice').onclick=solo;$('#retry').onclick=solo;$('#create').onclick=()=>enter(true);$('#join').onclick=()=>enter(false);$('#join').hidden=!client.room;$('#start').onclick=()=>client.send('start');$('#lock').onclick=()=>client.send('lock');$('#next').onclick=()=>{if(mode==='practice'){practice.next();lastTime=performance.now();render();}else client.send('next');};$('#pause').onclick=()=>{practice.paused=!practice.paused;lastTime=performance.now();if(practice.paused)window.CreatorAudio?.stop();render();};
function leave(){if(mode==='online')client.leave();mode='menu';state=null;practice=null;$('#room').hidden=true;$('#lobby').hidden=false;const u=new URL(location.href);u.searchParams.delete('room');history.replaceState(null,'',u);client.room=null;client.state=null;$('#join').hidden=true;notice('Choose practice or a private room.');}
$('#leave').onclick=leave;$('#back').onclick=leave;$('#reconnect').onclick=()=>client.connect();$('#copy').onclick=async()=>{try{await navigator.clipboard.writeText($('#invite').value);notice('Private invite copied.');}catch{$('#invite').select();notice('Copy the selected link.');}};
client.onDisconnect=()=>{if(mode==='online')render();};
document.addEventListener('keydown',e=>{if(e.repeat||e.target.closest('input,select,textarea,a'))return;if(/^Digit[1-4]$/.test(e.code)){e.preventDefault();answerQuestion(Number(e.code.at(-1))-1);}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){window.CreatorAudio?.stop();if(mode==='practice'){practice.paused=true;render();}}else if(mode==='online')client.sync();lastTime=performance.now();});
setInterval(()=>{const now=performance.now();if(mode==='practice'){const phase=practice.phase;practice.update(now-lastTime);if(phase!==practice.phase)render();}lastTime=now;tickText();},100);
$('#availability').textContent=client.endpoint?'Practice solo or invite 2–8 friends to a private match.':'Private rooms are temporarily unavailable. Solo practice is ready.';
window.quizSnapshot=()=>({mode,...(current()||{})});
if(client.room){let saved=false;try{saved=!!localStorage.getItem(client.key());}catch{}if(saved)enter(false);}
