import assert from 'node:assert/strict';
import {BlastGame,COLS,ROWS,FUSE} from '../games/blast/engine.mjs';
let checks=0;function check(name,fn){fn();checks++;console.log('PASS '+name);}
function empty(){const g=new BlastGame({seed:4,mode:'duo'});g.grid=g.grid.map(row=>row.map(t=>t===2?0:t));g.actors.forEach(a=>a.bot=false);g.start();return g;}
function tick(g,s){for(let t=0;t<s;t+=.02)g.step(.02);}
check('seeded maps and clear corner escape lanes',()=>{assert.deepEqual(new BlastGame({seed:5}).grid,new BlastGame({seed:5}).grid);for(let seed=0;seed<100;seed++){const g=new BlastGame({seed});for(const a of g.actors){assert.equal(g.tile(a.x,a.y),0);assert.equal([g.tile(a.x+(a.x===1?1:-1),a.y),g.tile(a.x,a.y+(a.y===1?1:-1))].filter(t=>t===0).length,2);}}});
check('walls block movement; cooldown prevents teleporting',()=>{const g=empty();assert.equal(g.move(0,3),false);assert.equal(g.move(0,1),true);assert.equal(g.move(0,1),false);tick(g,.2);assert.equal(g.move(0,2),false);});
check('bomb capacity, walking off a bomb, no re-entry',()=>{const g=empty();assert.equal(g.plant(0),true);assert.equal(g.plant(0),false);assert.equal(g.move(0,1),true);tick(g,.2);assert.equal(g.move(0,3),false);assert.equal(g.plant(0),false);});
check('fuse delay and owner self-damage',()=>{const g=empty();g.plant(0);tick(g,FUSE-.1);assert.equal(g.actors[0].alive,true);tick(g,.2);assert.equal(g.actors[0].alive,false);});
check('crates stop blast, destruct and can release items',()=>{const g=empty();g.actors[0].x=3;g.actors[0].y=3;g.actors[0].range=5;g.grid[3][5]=2;g.rng=()=>0;g.plant(0);tick(g,FUSE+.02);assert.equal(g.grid[3][5],0);assert.equal(g.onFire(5,3),true);assert.equal(g.onFire(6,3),false);assert.equal(g.items.get(3*COLS+5),'range');});
check('solid walls block flames',()=>{const g=empty();g.actors[0].x=1;g.actors[0].y=2;g.plant(0);tick(g,FUSE+.02);assert.equal(g.onFire(2,2),false);assert.equal(g.onFire(3,2),false);});
check('early chain reaction detonates a later bomb',()=>{const g=empty();g.actors[1].x=3;g.actors[1].y=1;g.plant(0);tick(g,.8);g.plant(1);tick(g,1.65);assert.equal(g.bombs.length,0);assert.equal(g.actors[1].alive,false);});
check('chain rays share crate snapshot',()=>{const g=empty();g.grid[3][3]=2;g.actors[0].x=1;g.actors[0].y=3;g.actors[0].range=6;g.actors[1].x=3;g.actors[1].y=1;g.actors[1].range=6;g.plant(0);g.plant(1);tick(g,FUSE+.02);assert.equal(g.onFire(4,3),false);assert.equal(g.onFire(3,4),false);});
check('power-ups increase capacity, range and speed',()=>{for(const item of ['bomb','range','speed']){const g=empty(),a=g.actors[0];g.items.set(COLS+2,item);g.move(0,1);assert.equal(g.items.size,0);assert.equal(item==='bomb'?a.capacity===2:item==='range'?a.range===3:a.speed<.16,true);}});
check('pause freezes the fuse',()=>{const g=empty();g.plant(0);g.pause();g.step(1);assert.equal(g.time,0);g.pause();g.step(.5);assert.equal(g.time,.5);});
check('last survivor wins, simultaneous final deaths draw',()=>{const g=empty();g.actors[2].alive=false;g.actors[3].alive=false;g.actors[1].x=3;g.actors[1].y=1;g.plant(0);tick(g,FUSE+.02);assert.equal(g.status,'over');assert.equal(g.result,null);const h=empty();h.actors.slice(1).forEach(a=>a.alive=false);h.step(.02);assert.equal(h.result,0);});
check('three-minute timeout is a draw',()=>{const g=empty();g.time=179.99;g.step(.02);assert.equal(g.status,'over');assert.equal(g.result,null);});
check('solo death ends the round immediately',()=>{const g=new BlastGame({seed:1});g.actors.forEach(a=>a.bot=false);g.start();g.plant(0);tick(g,2.5);assert.equal(g.status,'over');assert.equal(g.result,null);});
check('bots escape their first planted bomb on open map',()=>{const g=empty();const a=g.actors[2];a.bot=true;g.grid[3][11]=2;tick(g,3);assert.equal(a.alive,true);assert.ok(a.crates>0);});
check('100 seeded bot matches preserve arena invariants',()=>{let planted=0,crates=0;for(let seed=0;seed<100;seed++){const g=new BlastGame({seed,mode:'duo'});g.actors.forEach(a=>a.bot=true);g.start();for(let i=0;i<2400&&g.status==='playing';i++){g.step(.04);for(const a of g.actors){assert.ok(a.x>0&&a.x<COLS-1&&a.y>0&&a.y<ROWS-1);assert.equal(g.tile(a.x,a.y),0);}assert.equal(new Set(g.bombs.map(b=>b.y*COLS+b.x)).size,g.bombs.length);g.events=[];}planted+=g.serial;crates+=g.actors.reduce((n,a)=>n+a.crates,0);}assert.ok(planted>100);assert.ok(crates>100);console.log({planted,crates});});
console.log(`${checks} Blast mechanics checks passed.`);
