import assert from 'node:assert/strict';
import {createParty,addPlayer,partyAction,partySnapshot,advance,depart,cleanPack} from '../multiplayer/party-core.mjs';
let now=100000,checks=0;const check=(name,fn)=>{fn();checks++;console.log('PASS '+name);};
const r=createParty('draw',now),players=Array.from({length:8},(_,i)=>addPlayer(r,'token'+i,i===1?'<img onerror=bad>':'Player '+i,i,now));players.forEach(p=>p.offline=null);
const act=(id,type,extra={})=>partyAction(r,id,{type,id:crypto.randomUUID(),roundId:r.roundId,canvasVersion:r.canvasVersion,...extra},now);
check('eight-player cap',()=>assert.throws(()=>addPlayer(r,'extra','extra',0,now),/full/));
check('host authorization',()=>assert.throws(()=>act(players[1].id,'start'),/host/));
check('custom packs validated',()=>{assert.throws(()=>cleanPack([{word:'a',aliases:[]}]),/3/);assert.throws(()=>cleanPack([{word:'x',aliases:[]},{word:'x',aliases:[]},{word:'y',aliases:[]}]),/unique/);});
act(players[0].id,'pack',{pack:'custom',words:[{word:'bicycle',aliases:['bike']},{word:'cat',aliases:['kitty']},{word:'sun',aliases:['suraj']}]});act(players[0].id,'start');
check('start locks room and rotates oldest first',()=>{assert.equal(r.drawer,players[0].id);assert.equal(r.phase,'choose');assert.equal(r.locked,true);assert.throws(()=>addPlayer(r,'late','late',0,now),/locked/);});
check('only drawer receives choices',()=>{assert.equal(partySnapshot(r,r.drawer,now).choices.length,3);const s=partySnapshot(r,players[1].id,now);assert.ok(!('choices'in s));assert.ok(!JSON.stringify(s).includes('bicycle'));assert.ok(!JSON.stringify(s).includes('token'));});
check('guesser cannot choose',()=>assert.throws(()=>act(players[1].id,'choose',{choice:0}),/drawer/));
act(r.drawer,'choose',{choice:r.choices.findIndex(w=>w.word==='bicycle')});
check('only drawer receives word and nobody receives aliases',()=>{assert.equal(partySnapshot(r,r.drawer,now).word,'bicycle');assert.ok(!JSON.stringify(partySnapshot(r,players[1].id,now)).includes('bicycle'));assert.ok(!JSON.stringify(partySnapshot(r,r.drawer,now)).includes('bike'));});
check('unauthorized/stale strokes rejected',()=>{assert.throws(()=>act(players[1].id,'stroke'),/drawer/);assert.throws(()=>act(r.drawer,'stroke',{roundId:'stale'}),/earlier/);});
const stroke={stroke:'stroke-1',seq:0,color:'#173e38',size:7,points:[[0,0],[.5,.5],[1,1]]};act(r.drawer,'stroke',stroke);
check('validated bounded batches',()=>{assert.equal(r.points,3);assert.throws(()=>act(r.drawer,'stroke',stroke),/stale/);assert.throws(()=>act(r.drawer,'stroke',{...stroke,seq:1,points:[[2,0]]}),/Invalid/);assert.throws(()=>act(r.drawer,'stroke',{...stroke,points:Array(33).fill([0,0])}),/Invalid/);});
act(r.drawer,'undo');check('undo removes entire gesture',()=>assert.equal(r.points,0));act(r.drawer,'stroke',{...stroke,stroke:'stroke-2'});act(r.drawer,'clear');check('clear increments canvas version and removes history',()=>assert.equal(r.drawing.length,0));
const duplicate={type:'guess',id:crypto.randomUUID(),roundId:r.roundId,text:' BIKE '};partyAction(r,players[1].id,duplicate,now);
check('server normalizes aliases and scores once',()=>{assert.equal(players[1].score,300);assert.equal(players[0].score,50);assert.throws(()=>partyAction(r,players[1].id,duplicate,now),/Duplicate/);assert.throws(()=>act(players[1].id,'guess',{text:'bike'}),/cannot/);assert.ok(!JSON.stringify(partySnapshot(r,players[2].id,now)).includes('BIKE'));});
now+=41000;check('timed hint reveals only first letter',()=>assert.equal(partySnapshot(r,players[2].id,now).hint,'b _ _ _ _ _ _'));
now=r.deadline;advance(r,now);check('deadline closes guesses before accepting',()=>{assert.equal(r.phase,'reveal');assert.throws(()=>act(players[2].id,'guess',{text:'bike'}),/cannot/);assert.equal(partySnapshot(r,players[2].id,now).reveal,'bicycle');});
now=r.deadline;advance(r,now);check('fair rotation changes drawer',()=>assert.equal(r.drawer,players[1].id));
depart(r,players[0].id,now);check('host departure transfers host',()=>assert.equal(r.host,players[1].id));depart(r,players[1].id,now);check('drawer departure skips round',()=>assert.equal(r.phase,'reveal'));
for(let i=0;i<20&&r.phase!=='finished';i++){if(r.phase==='choose')act(r.drawer,'choose',{choice:0});now=r.deadline;advance(r,now);}
check('full match reaches final scores',()=>assert.equal(r.phase,'finished'));
act(r.host,'start');check('rematch resets scores',()=>assert.ok(r.players.every(p=>p.score===0)));
act(r.host,'kick',{player:players[7].id});check('host kick removes token/seat',()=>assert.ok(!r.players.some(p=>p.token==='token7')));
const bounded=createParty('draw',now);for(let i=0;i<3;i++)addPlayer(bounded,'limit'+i,'P'+i,0,now).offline=null;
const boundedAction=(type,extra={})=>partyAction(bounded,bounded.host,{type,id:crypto.randomUUID(),roundId:bounded.roundId,canvasVersion:bounded.canvasVersion,...extra},now);boundedAction('start');boundedAction('choose',{choice:0});
for(let seq=0;seq<250;seq++)boundedAction('stroke',{stroke:'long-stroke',seq,color:'#173e38',size:7,points:Array.from({length:32},()=>[.123456789,.987654321])});
check('8,000-point canvas bound enforced without dropping accepted ink',()=>{assert.equal(bounded.points,8000);assert.throws(()=>boundedAction('stroke',{stroke:'long-stroke',seq:250,color:'#173e38',size:7,points:[[0,0]]}),/full/);assert.equal(bounded.points,8000);assert.ok(JSON.stringify(bounded).length<500000);});
boundedAction('clear');for(let i=0;i<120;i++)boundedAction('stroke',{stroke:'s'+i,seq:0,color:'#173e38',size:7,points:[[0,0]]});check('120-gesture history cap enforced',()=>assert.throws(()=>boundedAction('stroke',{stroke:'extra',seq:0,color:'#173e38',size:7,points:[[0,0]]}),/limit/));
console.log(`${checks} Draw rule/security checks passed.`);
